services:
  api:
    container_name: explore-go-templ
    build:
      context: .
      target: api-dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"

  generate-template:
    container_name: explore-go-templ-generate
    build:
      context: .
      target: generate-templ
    volumes:
      - ./:/app
